import '../models/food_item.dart';
import '../models/restaurant.dart';

class MockDataService {
  static List<Restaurant> getRestaurants() {
    return [
      Restaurant(
        id: '1',
        name: 'Pizza Palace',
        description: 'Authentic Italian pizza with fresh ingredients',
        imageUrl: 'https://picsum.photos/400/300?random=1',
        rating: 4.5,
        reviewCount: 1247,
        cuisine: 'Italian',
        deliveryTime: 25,
        deliveryFee: 2.99,
        minimumOrder: 15.0,
        menu: [
          FoodItem(
            id: '1',
            name: 'Margherita Pizza',
            description: 'Fresh mozzarella, tomato sauce, and basil',
            price: 12.99,
            imageUrl: 'https://picsum.photos/300/200?random=2',
            category: 'Pizza',
            isVegetarian: true,
            preparationTime: 20,
          ),
          FoodItem(
            id: '2',
            name: 'Pepperoni Pizza',
            description: 'Classic pepperoni with mozzarella cheese',
            price: 14.99,
            imageUrl: 'https://picsum.photos/300/200?random=3',
            category: 'Pizza',
            preparationTime: 20,
          ),
          FoodItem(
            id: '3',
            name: 'Caesar Salad',
            description: 'Fresh romaine lettuce with caesar dressing',
            price: 8.99,
            imageUrl: 'https://picsum.photos/300/200?random=4',
            category: 'Salad',
            isVegetarian: true,
            preparationTime: 10,
          ),
        ],
      ),
      Restaurant(
        id: '2',
        name: 'Burger Junction',
        description: 'Gourmet burgers made with premium beef',
        imageUrl: 'https://picsum.photos/400/300?random=5',
        rating: 4.3,
        reviewCount: 892,
        cuisine: 'American',
        deliveryTime: 20,
        deliveryFee: 1.99,
        minimumOrder: 12.0,
        menu: [
          FoodItem(
            id: '4',
            name: 'Classic Cheeseburger',
            description: 'Beef patty with cheese, lettuce, tomato, and onion',
            price: 9.99,
            imageUrl: 'https://picsum.photos/300/200?random=6',
            category: 'Burger',
            preparationTime: 15,
          ),
          FoodItem(
            id: '5',
            name: 'Bacon Burger',
            description: 'Beef patty with crispy bacon and cheese',
            price: 11.99,
            imageUrl: 'https://picsum.photos/300/200?random=7',
            category: 'Burger',
            preparationTime: 15,
          ),
          FoodItem(
            id: '6',
            name: 'French Fries',
            description: 'Crispy golden french fries',
            price: 4.99,
            imageUrl: 'https://picsum.photos/300/200?random=8',
            category: 'Sides',
            isVegetarian: true,
            preparationTime: 8,
          ),
        ],
      ),
      Restaurant(
        id: '3',
        name: 'Sushi Zen',
        description: 'Fresh sushi and Japanese cuisine',
        imageUrl: 'https://picsum.photos/400/300?random=9',
        rating: 4.7,
        reviewCount: 1563,
        cuisine: 'Japanese',
        deliveryTime: 30,
        deliveryFee: 3.99,
        minimumOrder: 20.0,
        menu: [
          FoodItem(
            id: '7',
            name: 'California Roll',
            description: 'Crab, avocado, and cucumber roll',
            price: 8.99,
            imageUrl: 'https://picsum.photos/300/200?random=10',
            category: 'Sushi',
            preparationTime: 12,
          ),
          FoodItem(
            id: '8',
            name: 'Salmon Nigiri',
            description: 'Fresh salmon over seasoned rice',
            price: 12.99,
            imageUrl: 'https://picsum.photos/300/200?random=11',
            category: 'Sushi',
            preparationTime: 10,
          ),
          FoodItem(
            id: '9',
            name: 'Miso Soup',
            description: 'Traditional Japanese miso soup',
            price: 3.99,
            imageUrl: 'https://picsum.photos/300/200?random=12',
            category: 'Soup',
            isVegetarian: true,
            preparationTime: 5,
          ),
        ],
      ),
      Restaurant(
        id: '4',
        name: 'Taco Fiesta',
        description: 'Authentic Mexican tacos and burritos',
        imageUrl: 'https://picsum.photos/400/300?random=13',
        rating: 4.2,
        reviewCount: 743,
        cuisine: 'Mexican',
        deliveryTime: 18,
        deliveryFee: 2.49,
        minimumOrder: 10.0,
        menu: [
          FoodItem(
            id: '10',
            name: 'Chicken Tacos',
            description: 'Three soft tacos with grilled chicken',
            price: 7.99,
            imageUrl: 'https://picsum.photos/300/200?random=14',
            category: 'Tacos',
            preparationTime: 12,
          ),
          FoodItem(
            id: '11',
            name: 'Beef Burrito',
            description: 'Large burrito with seasoned beef and rice',
            price: 9.99,
            imageUrl: 'https://picsum.photos/300/200?random=15',
            category: 'Burrito',
            preparationTime: 15,
          ),
          FoodItem(
            id: '12',
            name: 'Guacamole',
            description: 'Fresh homemade guacamole',
            price: 4.99,
            imageUrl: 'https://picsum.photos/300/200?random=16',
            category: 'Sides',
            isVegetarian: true,
            preparationTime: 8,
          ),
        ],
      ),
    ];
  }

  static List<String> getCategories() {
    return [
      'All',
      'Pizza',
      'Burger',
      'Sushi',
      'Tacos',
      'Salad',
      'Sides',
      'Soup',
    ];
  }
}
